/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.foodie.foodviewapplication.vistas;


import com.foodie.foodviewapplication.modelo.Address;
import com.foodie.foodviewapplication.modelo.Department;
import com.foodie.foodviewapplication.modelo.Place;
import com.foodie.foodviewapplication.modelo.PlacePreferences;
import com.foodie.foodviewapplication.modelo.Preferences;
import com.foodie.foodviewapplication.modelo.Review;
import com.foodie.foodviewapplication.modelo.Town;
import com.foodie.foodviewapplication.modelo.User;
import com.foodie.foodviewapplication.service.AddressDAO;
import com.foodie.foodviewapplication.service.DepartmentDAO;
import com.foodie.foodviewapplication.service.FavoritePlacesDAO;
import com.foodie.foodviewapplication.service.PlaceDAO;
import com.foodie.foodviewapplication.service.PlaceListContentDAO;
import com.foodie.foodviewapplication.service.PlacePreferencesDAO;
import com.foodie.foodviewapplication.service.PreferencesDAO;
import com.foodie.foodviewapplication.service.ReviewDAO;
import com.foodie.foodviewapplication.service.TownDAO;
import com.foodie.foodviewapplication.service.UserDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan ortega
 */
public class Lugar extends javax.swing.JPanel {

    private Place place;
    private PlaceDAO placeDAO;
    private AddressDAO addressDAO;
    private Address address;
    private Town town;
    private TownDAO townDAO;
    private Department department;
    private DepartmentDAO departmentDAO;
    private Review review;
    private ReviewDAO reviewDAO;
    private User user;
    private UserDAO userDAO;
    private Preferences preferences;
    private PreferencesDAO preferencesDAO;
    private PlacePreferences placePreferences;
    private PlacePreferencesDAO placePreferencesDAO;
    private FavoritePlacesDAO favoritePlacesDAO;
    private PlaceListContentDAO placeListContentDAO;
    /**
     * Creates new form Lugar
     */
    public Lugar(String name) {
        
        placeDAO = new PlaceDAO();
        place = new Place();
        addressDAO = new AddressDAO();
        address = new Address();
        town = new Town();
        townDAO = new TownDAO();
        department = new Department();
        departmentDAO = new DepartmentDAO();
        review = new Review();
        reviewDAO = new ReviewDAO();
        user = new User();
        userDAO = new UserDAO();
        preferences = new Preferences();
        preferencesDAO = new PreferencesDAO();
        placePreferences = new PlacePreferences();
        placePreferencesDAO = new PlacePreferencesDAO();
        favoritePlacesDAO = new FavoritePlacesDAO();
        placeListContentDAO = new PlaceListContentDAO();
                
        
        
        initComponents();
        initLabels(name);
        obtenerReviewsTable(name);
        obtenerPreferencesTable(name);
        metrics(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoLugar = new javax.swing.JPanel();
        txtNombrePlace = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCelular = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCorreo = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jReviews = new javax.swing.JTable();
        txtNumReview = new javax.swing.JLabel();
        txtNumLikes = new javax.swing.JLabel();
        txtNumPlaceList = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPreferences = new javax.swing.JTable();
        txtMatch = new javax.swing.JLabel();
        bntLike = new javax.swing.JButton();

        fondoLugar.setBackground(new java.awt.Color(255, 255, 255));

        txtNombrePlace.setFont(new java.awt.Font("Corbel", 1, 60)); // NOI18N
        txtNombrePlace.setForeground(new java.awt.Color(102, 0, 0));
        txtNombrePlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePlace.setText("Nombre del Restaurante");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dirección:");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        txtCelular.setColumns(20);
        txtCelular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(51, 0, 0));
        txtCelular.setRows(5);
        txtCelular.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Celular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jScrollPane2.setViewportView(txtCelular);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        txtCorreo.setColumns(20);
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(51, 0, 0));
        txtCorreo.setRows(5);
        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jScrollPane3.setViewportView(txtCorreo);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contacto:");

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtDireccion.setRows(5);
        txtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ubicación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 0, 14))); // NOI18N
        jScrollPane4.setViewportView(txtDireccion);

        jScrollPane5.setForeground(new java.awt.Color(51, 0, 0));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reseñas del Restaurante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 0, 14), new java.awt.Color(51, 0, 0))); // NOI18N
        jScrollPane5.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        jReviews.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jReviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuario", "Puntaje", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jReviews);
        if (jReviews.getColumnModel().getColumnCount() > 0) {
            jReviews.getColumnModel().getColumn(1).setMinWidth(50);
            jReviews.getColumnModel().getColumn(1).setMaxWidth(50);
            jReviews.getColumnModel().getColumn(2).setMinWidth(100);
            jReviews.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        txtNumReview.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        txtNumReview.setForeground(new java.awt.Color(51, 0, 0));
        txtNumReview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNumReview.setToolTipText("");
        txtNumReview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "# Reviews", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 0, 14), new java.awt.Color(51, 0, 0))); // NOI18N

        txtNumLikes.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        txtNumLikes.setForeground(new java.awt.Color(51, 0, 0));
        txtNumLikes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNumLikes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "# Likes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 0, 14), new java.awt.Color(51, 0, 0))); // NOI18N
        txtNumLikes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtNumPlaceList.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        txtNumPlaceList.setForeground(new java.awt.Color(51, 0, 0));
        txtNumPlaceList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNumPlaceList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "# PlaceList", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 0, 14), new java.awt.Color(51, 0, 0))); // NOI18N
        txtNumPlaceList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtUbicacion.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        txtUbicacion.setForeground(new java.awt.Color(51, 0, 0));
        txtUbicacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ubicación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 0, 14), new java.awt.Color(51, 0, 0))); // NOI18N

        jScrollPane6.setForeground(new java.awt.Color(51, 0, 0));
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preferencias del Restaurante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 0, 14), new java.awt.Color(51, 0, 0))); // NOI18N
        jScrollPane6.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        jPreferences.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jPreferences.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Preferencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jPreferences);

        txtMatch.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        txtMatch.setForeground(new java.awt.Color(51, 0, 0));
        txtMatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMatch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Match", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 0, 14), new java.awt.Color(51, 0, 0))); // NOI18N
        txtMatch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bntLike.setBackground(new java.awt.Color(153, 153, 153));
        bntLike.setFont(new java.awt.Font("Corbel", 0, 10)); // NOI18N
        bntLike.setText("LIKE");
        bntLike.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLugarLayout = new javax.swing.GroupLayout(fondoLugar);
        fondoLugar.setLayout(fondoLugarLayout);
        fondoLugarLayout.setHorizontalGroup(
            fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLugarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLugarLayout.createSequentialGroup()
                        .addGroup(fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLugarLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(fondoLugarLayout.createSequentialGroup()
                                .addGroup(fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                                    .addGroup(fondoLugarLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)))
                        .addGroup(fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(fondoLugarLayout.createSequentialGroup()
                                .addComponent(txtNumReview, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumLikes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumPlaceList, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntLike, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addComponent(txtNombrePlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fondoLugarLayout.setVerticalGroup(
            fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLugarLayout.createSequentialGroup()
                .addComponent(txtNombrePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLugarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLugarLayout.createSequentialGroup()
                                .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLugarLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatch, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(txtNumPlaceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumLikes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(fondoLugarLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(bntLike, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLugarLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fondoLugarLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNombrePlace.getAccessibleContext().setAccessibleParent(txtNombrePlace);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLikeActionPerformed
        bntLike.setBackground(Color.GREEN);
        
    }//GEN-LAST:event_bntLikeActionPerformed
    
    private void initLabels(String name){
        
        place  = placeDAO.getPlaceByName(name);
        txtNombrePlace.setText(place.getNamePlace());
        txtDescripcion.setText(place.getDescription());
        txtCorreo.setText(place.getEmail());
        txtCelular.setText(place.getPhoneNumber());
        int fk_address = place.getFkIdAddress();
        address = addressDAO.getAddressById(fk_address);
        txtDireccion.setText(address.getStreet()+" "+address.getStreetNumber()+" "+address.getStreetComplement()+", Barrio:"+address.getNeighborhood());
        town = townDAO.getTownById(address.getFkIdTown());
        department = departmentDAO.getDepartmentById(town.getFkIdDepartment());
        txtUbicacion.setText(town.getName()+"-"+department.getName());
    }
    
    public void obtenerReviewsTable(String name) {
        try {
            // Obtener todos los lugares desde el DAO
            place  = placeDAO.getPlaceByName(name);
            List<Review> reviews = reviewDAO.getAllReviewsForPlace(place.getIdPlace());

            // Obtener el modelo de la tabla y resetear su contenido
            DefaultTableModel model = (DefaultTableModel) jReviews.getModel();
            model.setRowCount(0);

            // Iterar sobre la lista de lugares y añadir filas al modelo de la tabla
            for (Review review : reviews) {
                try {
                    user = userDAO.getUserById(review.getFkIdUser());
                    Object[] registro = {
                        String.valueOf(user.getGivenName()+" "+user.getFamilyName()),
                        review.getStars(),
                        String.valueOf(review.getDate())
                    };

                    // Añadir el registro al modelo de la tabla
                    model.addRow(registro);
                } catch (Exception e) {
                    e.printStackTrace();
                    
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            // Manejo de errores al obtener los lugares
            JOptionPane.showMessageDialog(null, "Error al obtener las reseñas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void obtenerPreferencesTable(String name) {
        try {
            // Obtener todos los lugares desde el DAO
            place  = placeDAO.getPlaceByName(name);
            List<PlacePreferences> placePreference = placePreferencesDAO.getPlacePreferencesByPlaceId(place.getIdPlace());

            // Obtener el modelo de la tabla y resetear su contenido
            DefaultTableModel model = (DefaultTableModel) jPreferences.getModel();
            model.setRowCount(0);

            // Iterar sobre la lista de lugares y añadir filas al modelo de la tabla
            for (PlacePreferences placePreferences : placePreference) {
                try {
                    preferences = preferencesDAO.getPreferencesById(placePreferences.getFkIdPreferences());
                    Object[] registro = {
                        preferences.getName()
                    };

                    // Añadir el registro al modelo de la tabla
                    model.addRow(registro);
                } catch (Exception e) {
                    e.printStackTrace();
                    
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            // Manejo de errores al obtener los lugares
            JOptionPane.showMessageDialog(null, "Error al obtener las reseñas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void contarLikes(String name){
        place  = placeDAO.getPlaceByName(name);
        int likes = favoritePlacesDAO.countLikesByPlace(place.getIdPlace());
        String likesSt = String.valueOf(likes);
        txtNumLikes.setText(likesSt);
    }
    
    private void contarReview(String name){
        place  = placeDAO.getPlaceByName(name);
        int reviews = reviewDAO.countReviewsByPlace(place.getIdPlace());
        String reviewsSt = String.valueOf(reviews);
        txtNumReview.setText(reviewsSt);
    }
    
    private void contarPlaceList(String name){
        place  = placeDAO.getPlaceByName(name);
        int placeList = placeListContentDAO.countPlaceListsByPlace(place.getIdPlace());
        String placeListSt = String.valueOf(placeList);
        txtNumPlaceList.setText(placeListSt);
    }
    
    private void metrics(String name){
        contarReview(name);
        contarLikes(name);
        contarPlaceList(name);
    }
            
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntLike;
    public javax.swing.JPanel fondoLugar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable jPreferences;
    private javax.swing.JTable jReviews;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTextArea txtCelular;
    public javax.swing.JTextArea txtCorreo;
    public javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JLabel txtMatch;
    public javax.swing.JLabel txtNombrePlace;
    private javax.swing.JLabel txtNumLikes;
    private javax.swing.JLabel txtNumPlaceList;
    private javax.swing.JLabel txtNumReview;
    private javax.swing.JLabel txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
